services:
  - type: web
    name: ecommerce-backend-api
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        value: super_secret_jwt_key_2026_pk_ecom_auth
      - key: MONGODB_URI
        value: mongodb+srv://samiullahnawaz942_db_user:IIJUllXitmg0FnhA@cluster0.2didtxe.mongodb.net/ecommerce_db?retryWrites=true&w=majority&appName=Cluster0
