"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const authController_1 = require("../controllers/authController");
const auth_1 = require("../middleware/auth");
const router = (0, express_1.Router)();
router.post('/register', authController_1.registerCustomer);
router.post('/login', authController_1.loginCustomer);
router.post('/admin/login', authController_1.loginAdmin);
router.post('/forgot-password', authController_1.forgotPassword);
router.post('/verify-otp', authController_1.verifyOtpCode);
router.post('/reset-password', authController_1.resetPassword);
router.get('/me', auth_1.protect, authController_1.getMe);
exports.default = router;
